export const GET_ARTICLELIST = "GET_ARTICLELIST";
export const GET_ARTICLELIST_BY_TAG = "GET_ARTICLELIST_BY_TAG";
export const GET_TAGLIST = "GET_TAGLIST";
export const FETCHDATASTART = "FETCHDATASTART";

export type GET_ARTICLELIST = typeof GET_ARTICLELIST;
export type GET_ARTICLELIST_BY_TAG = typeof GET_ARTICLELIST_BY_TAG;
export type GET_TAGLIST = typeof GET_TAGLIST;
export type FETCHDATASTART = typeof FETCHDATASTART;